import "jsr:@supabase/functions-js/edge-runtime.d.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2"

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders })
  }

  try {
    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
      { auth: { autoRefreshToken: false, persistSession: false } },
    )

    // Verify caller is admin
    const authHeader = req.headers.get("Authorization") ?? ""
    const token = authHeader.replace("Bearer ", "")
    const { data: { user }, error: userErr } = await supabaseAdmin.auth.getUser(token)
    if (userErr || !user) {
      return json({ error: "Not authenticated" }, 401)
    }

    const { data: profile } = await supabaseAdmin
      .from("profiles")
      .select("role")
      .eq("id", user.id)
      .single()

    if (profile?.role !== "admin") {
      return json({ error: "Admin access required" }, 403)
    }

    const { email, role, siteIds, redirectTo } = await req.json()

    if (!email || !role) {
      return json({ error: "email and role are required" }, 400)
    }

    // Create invitation record (token auto-generated by DB default)
    const { data: invitation, error: invErr } = await supabaseAdmin
      .from("invitations")
      .insert({ email, role, site_ids: siteIds ?? [], invited_by: user.id })
      .select()
      .single()

    if (invErr) {
      return json({ error: invErr.message }, 400)
    }

    // Send Supabase Auth invite email.
    // Embed role + site_ids in user metadata so handle_new_user trigger applies them on first sign-in.
    const { error: authErr } = await supabaseAdmin.auth.admin.inviteUserByEmail(email, {
      redirectTo,
      data: { role, site_ids: siteIds ?? [], invitation_token: invitation.token },
    })

    if (authErr) {
      // Clean up invitation record if auth invite failed
      await supabaseAdmin.from("invitations").delete().eq("id", invitation.id)
      return json({ error: authErr.message }, 400)
    }

    return json({ success: true })
  } catch (err) {
    return json({ error: err instanceof Error ? err.message : "Unknown error" }, 500)
  }
})

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  })
}
